### ISSUE TITLE
This package is not correctly configured for ESM.

### ISSUE THREAD

**Issue by itstheandre** [soc221b/zod-schema-faker#189]
Hey there!

First of all, great thing that you have created! I was using `zod-mock` before, but your library made it possible to address specific things that the other couldnt. Ie: `endsWith`, `toUpperCase`, etc. So great job on that!

I see that in the package.json you configured it to be `"type": "module"` however, the builds are done using CJS. When importing this file in an ESM codebase, even though it is able to import the named functions in the runtime, it is not able to be recognised by TSServer

**Comment by soc221b** [comment]
Hi, thank you for this report!! 😄 

I've tried to reproduce this issue, but it works for me: here is the [repo](https://github.com/soc221b/zod-schema-faker-189).

Could you please create a small reproducible repo?

Thank you.

**Comment by itstheandre** [comment]
From a brief look into your code, its because in `ESM`, you have to add the file suffix to the file. Specifically in `dist/zod-schema-faker.d.ts` (i know it is generated code)  you are just `export * from './index'` and in an ESM codebase this does not get recognized. Or so it seems

**Comment by itstheandre** [comment]
I think in your case, its because you are using `moduleResolution` `Bundler` and it works. The moment you don't use `Bundler`, but use `NodeNext` instead it no longer recognizes it.

I assume it might Skill Issue on my side tho :)

**Comment by itstheandre** [comment]
I can try to create a repro yeah. One sec

**Comment by itstheandre** [comment]
@soc221b here it is : https://github.com/itstheandre/zod-schema-faker-repro

**Comment by soc221b** [comment]
I’ll fix it in the next few days. Thank you for providing the reproducible repo.

(UTC+8)

**Comment by itstheandre** [comment]
No problem at all! I really appreciate the lib :) Keep up the great work
